### ISSUE TITLE
似乎需要浏览器一直运行？

### ISSUE THREAD

**Issue by x1a0** [MaskRay/wechatircd#10]
如果没理解错的话这个方案需要一个浏览器一直运行着？
（最近也在研究打造类似的通道，还没什么好想法）

**Comment by zTrix** [comment]
没错。。所以 maskray 写了一个博客用 x2go 跑在远程服务器上

https://maskray.me/blog/2016-07-06-wechatircd-webqqircd-without-scanning-qrcode-daily

**Comment by x1a0** [comment]
@zTrix 感谢，x2go方案初见成效，继续配置中...
