### ISSUE TITLE
A script on this page may be busy, or it may have stopped responding. You can stop the script now, open the script in the debugger, or let the script continue.

### ISSUE THREAD

**Issue by zTrix** [MaskRay/wechatircd#12]
![image](https://cloud.githubusercontent.com/assets/471934/17519810/105e1470-5e80-11e6-835c-a5a54662c668.png)

**Comment by zTrix** [comment]
Possible reason?

**Comment by x1a0** [comment]
Maybe the VM is way too slow... 😏

**Comment by zTrix** [comment]
open `about:config` in firefox, set the following will resolve this issue

```
dom.max_chrome_script_run_time = 200
dom.max_script_run_time = 200
```

@MaskRay Maybe you can put this into readme.
