### ISSUE TITLE
Got error in google chrome

### ISSUE THREAD

**Issue by jeffrey4l** [MaskRay/wechatircd#25]
Got following error message in google chrome. it works before. But not recently

I am using the latest code + google chrome 55 + archlinux

```
webwxApp31e225.js:3 Uncaught TypeError: angular.extend is not a function
    at Object.setUserInfo (webwxApp31e225.js:3)
    at webwxApp31e225.js:1
    at c (libs31e225.js:5)
    at libs31e225.js:5
    at c.$eval (libs31e225.js:5)
    at c.$digest (libs31e225.js:5)
    at c.$apply (libs31e225.js:5)
    at u (libs31e225.js:5)
    at m (libs31e225.js:5)
    at XMLHttpRequest.w.onreadystatechange (libs31e225.js:5)
```

**Comment by MaskRay** [comment]
This may be caused by a timing issue when `injector.js` is executed after `webwxApp31e225.js`. My knowledge on Angular.js is too shallow to figure out a more effective approach to inject code...

You can just reload the page and hopefully it will not display this error message.

**Comment by jeffrey4l** [comment]
How about load the injector.js slow enough? 

like

```
setTimeout(function(){load injector.js}), 20000)
```

**Comment by MaskRay** [comment]
I think you need to load `webwxApp31e225.js` after `injector.js`.

**Comment by jeffrey4l** [comment]
hrm, then no idea.
reload `webwxApp31e225.js` when `injector.js` is loaded.

**Comment by MaskRay** [comment]
Reloading `webwxApp31e225.js` does nothing as `webwxApp31e225.js` has already defined `angular` when it is loaded the first time.

**Comment by MaskRay** [comment]
Obsoleted as userscript has been used.
