### ISSUE TITLE
真的可以做到永远保持登录不再扫码？

### ISSUE THREAD

**Issue by hexsum** [MaskRay/wechatircd#28]
看到文档里有这么一句：

> If you cannot tolerant scanning QR codes with your phone everyday, see 无需每日扫码的IRC版微信和QQ：wechatircd、webqqircd.

真的可以做到永远保持登录不再扫码？

**Comment by MaskRay** [comment]
> 真的可以做到永远保持登录不再扫码？

之前有朋友反馈网络稳定的话，北京联通半个月连接不断不需扫码。我是放在VPS上的，最近几次扫码在2-12 2-09 1-24 1-16。

**Comment by hexsum** [comment]
微信倒是可以 qq现在不行了

**Comment by MaskRay** [comment]
QQ我已经放弃了……服务器特别不稳定，都没法坚持半小时不掉线，发送消息也经常收不到。好在用得极少，就不用了。

**Comment by hexsum** [comment]
我这边还有在用，一次扫码可以保持2天左右，收发消息暂时还算稳定

**Comment by MaskRay** [comment]
除了x2go还可以用xvfb + screenshot来显示QR码，我改了下文档～

<https://github.com/MaskRay/wechatircd/blob/dev/README.zhs.md#user-content-linux下headless浏览器>

折腾的乐趣。。

最近折腾的改善IRC体验的东西(很多是纯折腾)...

- server建立和微信网页版的绑定，而不是client登录后做。又全面修缮支持多clients，这样可以外接bot (目前看起来sopel还算方便)
- `--irc-nicks ray ray1`，给客户端保留的nick。防止微信用户占用这些名字
- `/mode +m`, `--join new`模式下防止自动重新join。用`/mode -m`撤销
- `/motd`，查看本repo最近5个commits
- `/squit $any`，log out
- 联系人带有mode `+v` (voice, 通常显示为前缀`+`)。`SpecialChannel#update_detail`
- `nick0: nick1: test`会被转换成`@GroupAlias0 @GroupAlias1 test`，`GroupAlias0` 是那个用户自己设置的名字，不是你设置的`Set Remark and Tag`，对应移动端的`On-screen names`
- 回复12:34:SS的消息：`@1234 !m multi\nline\nreply`，会发送`「Re GroupAlias: text」text`
- 回复12:34:56的消息：`!m @123456 multi\nline\nreply`
- 回复朋友/群的倒数第二条消息：`@2 reply`

IRC 3.1 3.2的`server-time`，让客户端显示消息时和服务器收到的消息的时刻一致。
