### ISSUE TITLE
用 phatomjs 可以做到 headless 吗？

### ISSUE THREAD

**Issue by sbilly** [MaskRay/wechatircd#29]
用 phatomjs 可以做到 headless 吗？毕竟需要 firefox／chrome 这种还是太费劲了。

**Comment by MaskRay** [comment]
https://github.com/MaskRay/wechatircd/blob/dev/README.zhs.md 里有一节写headless设置。可以用xvfb-run放firefox/chrome。phantomjs用的webkit JavaScript支持比较旧……injector.js里有些语法不支持。
