### ISSUE TITLE
终于发现志同道合之人，我也有个微信irc的实现，可以多交流

### ISSUE THREAD

**Issue by hexsum** [MaskRay/wechatircd#3]
http://github.com/sjdy521/Mojo-Weixin

**Comment by MaskRay** [comment]
赞，通过你的链接我也找到好多类似资源 https://github.com/geeeeeeeeek/electronic-wechat https://github.com/Urinx/WeixinBot https://github.com/lu4kyd0y/WeChat-Cloud-Robot  
Mojo-Webqq好棒，终于解决了我用QQ的苦恼了(折腾中)……

**Comment by hexsum** [comment]
关于怎么使用irc我的教程写的不够清楚，很多人还不太知道怎么用，我得抓紧时间把文档完善下
