### ISSUE TITLE
Websocket URL in injector.js or injector.user.js should consistent with '-l' parameter of wechatircd.py

### ISSUE THREAD

**Issue by yuchangyuan** [MaskRay/wechatircd#30]
When start wechatircd.py on remote server, listen on non-127.0.0.1 ip address, the injector.js should not use 127.0.0.1 as WS URL, and should use the IP address the http server listen to.

**Comment by MaskRay** [comment]
Thank you for reporting this! Does the latest commit from `dev` branch address this issue? Merge it later if it does.
