### ISSUE TITLE
Unable to login WeChat Web anymore.

### ISSUE THREAD

**Issue by Determinant** [MaskRay/wechatircd#33]
I suddenly lost my wechatircd channels today. It resulted in being unabe to login my account even directly through WeChat Web: "Your login may be compromised. For account security, you cannot log in to Web WeChat. You can try mobile WeChat or Windows WeChat".

Any way to resolve this? I guess some behavior of wechatircd caused the WeChat to suspect and revoke my web access permission.

**Comment by MaskRay** [comment]
Many other wechatircd/ehForwarderBot/itchat/Mojo-Weixin/wechaty users have also experienced this. WeChat obviously analyzes user behavior and our abnormal behaviors (keeping logged in for a long time. My Web WeChat sessions could usually last 2 to 3 weeks) cause the blockage.

```
规则不透明，无申诉渠道，这两天比较致命
全封还有解封渠道呢..这个只封web完全没有...

03:00  不推荐用常用号登录酷Q，腾讯最近管理很严，有封号的可能
03:07  你们是不是用不了了？
04:50  被封号了不是正好有正当理由不用了么… 🌚
04:51  「Re : 被封号了不是正好...」还是可以继续用手机客户端🌚
04:51  不推荐用常用号登录酷Q，腾讯最近管理很严，有封号的可能
04:51  我是说这个…
04:52  比起说一串乱七八糟的理由跟别人解释不用… 直接说「我号被封了以后都不用了」更有信服力… 🌚
04:52  🌚好吧我误会了
04:53  要不是公司用qq我早就放弃了
05:25  「Re : 比起说一串乱七八...」你咋被封号了？然后更多疑问..
05:25  说被盗了比较科学，找不回的那种
05:27  「Re : 比起说一串乱七八...」不不不
```

https://github.com/blueset/ehForwarderBot/wiki/EWS:-Current-reports-regarding-potential-actions-that-triggers-Web-WeChat-ban

My account was also banned, so I use WeChat less often these days.

https://github.com/sjdy521/Mojo-Weixin/issues/125

**Comment by Determinant** [comment]
Sigh..Really don't know what Tencent is thinking about...
