### ISSUE TITLE
微信上的中文昵称怎么在irc上显示

### ISSUE THREAD

**Issue by hexsum** [MaskRay/wechatircd#5]
想起来个问题，现在流行的irc服务器都不支持中文昵称，不知道这个项目里的的irc是否支持中文昵称
如果不支持，微信上的群名称、好友名称等是怎么在irc上对应的

**Comment by MaskRay** [comment]
根据RFChttps://tools.ietf.org/html/rfc2812#section-2.3.1，只有少数字符不能用作channel name，大概是：   /^[#!&+][^\x00\x07\x0a\x0d ,:]{0,50}$"/

nick的限制有点奇葩： nickname   =  ( letter / special ) *8( letter / digit / special / "-" ) 最多只能用9个字符，但似乎很多irc server长度限制都很宽松。wechatircd支持中文昵称，允许如下的nick：

``` python
    valid_nickname = re.compile(r"^[][\`_^{|}A-Za-z][][\`_^{|}A-Za-z0-9-]{0,50}$")
```

**Comment by hexsum** [comment]
我看你这个ircd的功能比较完备一些，我为了能支持中文昵称，也是自己实现了一个，只能支持很少的功能，我准备把你这个ircd单独拿出来挂在服务器上，以后和我的朋友聊irc就方便很多啦~

**Comment by MaskRay** [comment]
localhost还好，部署到公共服务器上有些vulnerabilities... 比如 `/dcc send nick/channel filename` 没有超时，可能被人当作代理。 普通 IRC channel 人数过多广播性能会非常低。等等～我想想怎么搞错误处理～
