### ISSUE TITLE
osx, No module called aiohttp 以及 module 'ssl' has no attribute 'PROTOCOL_TLSv1_2'

### ISSUE THREAD

**Issue by zhmiao** [MaskRay/wechatircd#8]
试了几次都不行，我试过`pip uninstall aiohttp` 然后`pip install --user aiohtto`， 这个模组可以被载入了。然后别的模组又认不出来。我试了把所有模组用`--user`安装了一边，`./wechatircd.py --tle-cert a.crt --tls-key a.key`总算能运行了，但是出现错误：`module 'ssl' has no attribute 'PROTOCOL_TLSv1_2'`。找不到解决这个问题的办法

**Comment by MaskRay** [comment]
http://stackoverflow.com/questions/30674900/is-it-possible-to-use-protocol-tlsv1-2-in-python-3-2-5

可以把`PROTOCOL_TLSv1_2`换成其他的

**Comment by zhmiao** [comment]
请问具体是怎么设置的？链接里说openssl的版本不对？

**Comment by MaskRay** [comment]
可能是osx的openssl版本低了，不支持这个协议。这里对 TLS 版本没有要求的，只是用上加密让浏览器不要报错(当然版本太低可能也会警告……)

**Comment by zhmiao** [comment]
看来还是不行，我的openssl版本是1.0.2的。我试了不用tls直接`./wechatircd.py`，输入指令后terminal似乎没有反应，我用weechat连接127.1:6667也连接不上。但是用127.1就连上了。我觉得这个以后可能在文档里可以提一下。

**Comment by ranranking** [comment]
还有“把`webwxapp.js`中`var ws = new MyWebSocket('wss://127.0.0.1:9000')`修改成`ws://127.0.0.1:9000`”这句话不会是把整个`var`这行都替换掉吧？我只替换了括号里的值

**Comment by ranranking** [comment]
我明白了，我在连的时候换成`127.1`就连上了

**Comment by zhmiao** [comment]
现在的问题是用了那个从新调转的插件，微信网页加载不出二维码。不调转就能看到二维码，这是为什么？

**Comment by MaskRay** [comment]
weechat使用`/server add wechat 127.1/6667`，不用冒号。

devtools console有没有错误输出？

**Comment by zhmiao** [comment]
有的。
<img width="553" alt="screen shot 2016-03-28 at 10 16 32 am" src="https://cloud.githubusercontent.com/assets/7812475/14082613/33dae304-f4ce-11e5-9d1d-25b77122ad28.png">
这个错误怎么解决？

**Comment by MaskRay** [comment]
这个错误是因为浏览器不允许HTTPS页面加载HTTP的js

你Mac OS X的openssl版本可能不支持TLS 1.2，你试试换成`ssl.PROTOCOL_TLSv1_1` `ssl.PROTOCOL_TLSv1`。

**Comment by zhmiao** [comment]
请问具体应该如何操作来替换tls版本？我现在不是使用tsl连接的。

**Comment by MaskRay** [comment]
仍然用HTTPS、WebSocket over TLS节描述的方法

把`wechatircd.py`中`PROTOCOL_TLSv1_2`改成`ssl.PROTOCOL_TLSv1_1`或`ssl.PROTOCOL_TLSv1`

**Comment by zhmiao** [comment]
不好意思，连上了，非常感谢帮助！

**Comment by zhmiao** [comment]
另外，请问如何使用weechat看图片？虽然这可能和这个项目不是很相关

**Comment by MaskRay** [comment]
https://github.com/glowing-bear/glowing-bear/ 是 weechat 的一个网页前端，可以预览图片。终端的话只能手动点击链接了……

**Comment by zhmiao** [comment]
哈哈哈，好吧，谢谢啦！
