### ISSUE TITLE
请问应当如何使用文档中那个.service文件？

### ISSUE THREAD

**Issue by zhmiao** [MaskRay/wechatircd#9]
要连微信的话我现在是先运行wechatircd.py然后从新开窗口运行irc。请问是否有办法在irc中自动运行这个监听程序？我看到文档最后有一个.service文件的介绍，可惜我用的是osx，没有systemd。请问你知道怎么写launchd的脚本吗？不然的话我就自己去看看怎么写吧。谢谢！

**Comment by MaskRay** [comment]
https://wiki.archlinux.org/index.php/Systemd/User

https://github.com/MaskRay/Config/tree/master/home/.config/systemd/user

**Comment by MaskRay** [comment]
好吧……你是Mac Os X，我不知道

**Comment by zhmiao** [comment]
好的，那我就试试去看看怎么弄launchd吧。在linux下只要有那个wechatircd.service的文件就可以开机自动运行那个监听程序了对吗？会开启任何窗口吗还是在背景运行？

**Comment by MaskRay** [comment]
要折腾systemd user让它自动启动的

**Comment by zhmiao** [comment]
原来如此，谢谢啦，我去试试
